/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2021-05-11 08:49:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1620394038000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("    <meta name=\"description\" content=\"\" />\r\n");
      out.write("    <meta name=\"author\" content=\"\" />\r\n");
      out.write("    <title>BetterCrypt</title>\r\n");
      out.write("    <!-- Favicon-->\r\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"assets/BetterCryptLogo.ico\" />\r\n");
      out.write("    <!-- Font Awesome icons (free version)-->\r\n");
      out.write("    <script src=\"https://use.fontawesome.com/releases/v5.15.3/js/all.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <!-- Simple line icons-->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.5.5/css/simple-line-icons.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <!-- Google fonts-->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("    <link href=\"css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Title</title>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0\" crossorigin=\"anonymous\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-light bg-light static-top\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"index.jsp\">BetterCrypt</a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("            <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                        Text\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"text-encrypt.jsp\">Encrypt</a></li>\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"text-decrypt.jsp\">Decrypt</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown1\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                        Image\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"image-encrypt.jsp\">Encrypt</a></li>\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"image-decrypt.jsp\">Decrypt</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<header class=\"masthead text-white text-center\">\r\n");
      out.write("    <div class=\"overlay\"></div>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-xl-9 mx-auto\"><h1 class=\"mb-5\">Build a landing page for your business or project and generate more leads!</h1></div>\r\n");
      out.write("            <div class=\"col-md-10 col-lg-8 col-xl-7 mx-auto\">\r\n");
      out.write("                <form>\r\n");
      out.write("                    <div class=\"form-row\">\r\n");
      out.write("                        <div class=\"col-12 col-md-9 mb-2 mb-md-0\"><input class=\"form-control form-control-lg\" type=\"email\" placeholder=\"Enter your email...\" /></div>\r\n");
      out.write("                        <div class=\"col-12 col-md-3\"><button class=\"btn btn-block btn-lg btn-primary\" type=\"submit\">Sign up!</button></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("<!-- Icons Grid-->\r\n");
      out.write("<section class=\"features-icons bg-light text-center\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-4\">\r\n");
      out.write("                <div class=\"features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3\">\r\n");
      out.write("                    <div class=\"features-icons-icon d-flex\"><i class=\"icon-screen-desktop m-auto text-primary\"></i></div>\r\n");
      out.write("                    <h3>Fully Responsive</h3>\r\n");
      out.write("                    <p class=\"lead mb-0\">This theme will look great on any device, no matter the size!</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4\">\r\n");
      out.write("                <div class=\"features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3\">\r\n");
      out.write("                    <div class=\"features-icons-icon d-flex\"><i class=\"icon-layers m-auto text-primary\"></i></div>\r\n");
      out.write("                    <h3>Bootstrap 4 Ready</h3>\r\n");
      out.write("                    <p class=\"lead mb-0\">Featuring the latest build of the new Bootstrap 4 framework!</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4\">\r\n");
      out.write("                <div class=\"features-icons-item mx-auto mb-0 mb-lg-3\">\r\n");
      out.write("                    <div class=\"features-icons-icon d-flex\"><i class=\"icon-check m-auto text-primary\"></i></div>\r\n");
      out.write("                    <h3>Easy to Use</h3>\r\n");
      out.write("                    <p class=\"lead mb-0\">Ready to use with your own content, or customize the source files!</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("<!-- Image Showcases-->\r\n");
      out.write("<section class=\"showcase\">\r\n");
      out.write("    <div class=\"container-fluid p-0\">\r\n");
      out.write("        <div class=\"row no-gutters\">\r\n");
      out.write("            <div class=\"col-lg-6 order-lg-2 text-white showcase-img\" style=\"background-image: url('assets/img/bg-showcase-1.jpg')\"></div>\r\n");
      out.write("            <div class=\"col-lg-6 order-lg-1 my-auto showcase-text\">\r\n");
      out.write("                <h2>Fully Responsive Design</h2>\r\n");
      out.write("                <p class=\"lead mb-0\">When you use a theme created by Start Bootstrap, you know that the theme will look great on any device, whether it's a phone, tablet, or desktop the page will behave responsively!</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row no-gutters\">\r\n");
      out.write("            <div class=\"col-lg-6 text-white showcase-img\" style=\"background-image: url('assets/img/bg-showcase-2.jpg')\"></div>\r\n");
      out.write("            <div class=\"col-lg-6 my-auto showcase-text\">\r\n");
      out.write("                <h2>Updated For Bootstrap 4</h2>\r\n");
      out.write("                <p class=\"lead mb-0\">Newly improved, and full of great utility classes, Bootstrap 4 is leading the way in mobile responsive web development! All of the themes on Start Bootstrap are now using Bootstrap 4!</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row no-gutters\">\r\n");
      out.write("            <div class=\"col-lg-6 order-lg-2 text-white showcase-img\" style=\"background-image: url('assets/img/bg-showcase-3.jpg')\"></div>\r\n");
      out.write("            <div class=\"col-lg-6 order-lg-1 my-auto showcase-text\">\r\n");
      out.write("                <h2>Easy to Use & Customize</h2>\r\n");
      out.write("                <p class=\"lead mb-0\">Landing Page is just HTML and CSS with a splash of SCSS for users who demand some deeper customization options. Out of the box, just add your content and images, and your new landing page will be ready to go!</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("<!-- Testimonials-->\r\n");
      out.write("<section class=\"testimonials text-center bg-light\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h2 class=\"mb-5\">What people are saying...</h2>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-4\">\r\n");
      out.write("                <div class=\"testimonial-item mx-auto mb-5 mb-lg-0\">\r\n");
      out.write("                    <img class=\"img-fluid rounded-circle mb-3\" src=\"assets/img/testimonials-1.jpg\" alt=\"...\" />\r\n");
      out.write("                    <h5>Margaret E.</h5>\r\n");
      out.write("                    <p class=\"font-weight-light mb-0\">\"This is fantastic! Thanks so much guys!\"</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4\">\r\n");
      out.write("                <div class=\"testimonial-item mx-auto mb-5 mb-lg-0\">\r\n");
      out.write("                    <img class=\"img-fluid rounded-circle mb-3\" src=\"assets/img/testimonials-2.jpg\" alt=\"...\" />\r\n");
      out.write("                    <h5>Fred S.</h5>\r\n");
      out.write("                    <p class=\"font-weight-light mb-0\">\"Bootstrap is amazing. I've been using it to create lots of super nice landing pages.\"</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4\">\r\n");
      out.write("                <div class=\"testimonial-item mx-auto mb-5 mb-lg-0\">\r\n");
      out.write("                    <img class=\"img-fluid rounded-circle mb-3\" src=\"assets/img/testimonials-3.jpg\" alt=\"...\" />\r\n");
      out.write("                    <h5>Sarah W.</h5>\r\n");
      out.write("                    <p class=\"font-weight-light mb-0\">\"Thanks so much for making these free resources available to us!\"</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("<!-- Call to Action-->\r\n");
      out.write("<section class=\"call-to-action text-white text-center\">\r\n");
      out.write("    <div class=\"overlay\"></div>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-xl-9 mx-auto\"><h2 class=\"mb-4\">Ready to get started? Sign up now!</h2></div>\r\n");
      out.write("            <div class=\"col-md-10 col-lg-8 col-xl-7 mx-auto\">\r\n");
      out.write("                <form>\r\n");
      out.write("                    <div class=\"form-row\">\r\n");
      out.write("                        <div class=\"col-12 col-md-9 mb-2 mb-md-0\"><input class=\"form-control form-control-lg\" type=\"email\" placeholder=\"Enter your email...\" /></div>\r\n");
      out.write("                        <div class=\"col-12 col-md-3\"><button class=\"btn btn-block btn-lg btn-primary\" type=\"submit\">Sign up!</button></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("<!-- Footer-->\r\n");
      out.write("<footer class=\"footer bg-light\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-6 h-100 text-center text-lg-left my-auto\">\r\n");
      out.write("                <ul class=\"list-inline mb-2\">\r\n");
      out.write("                    <li class=\"list-inline-item\"><a href=\"#!\">About</a></li>\r\n");
      out.write("                    <li class=\"list-inline-item\">â</li>\r\n");
      out.write("                    <li class=\"list-inline-item\"><a href=\"#!\">Contact</a></li>\r\n");
      out.write("                    <li class=\"list-inline-item\">â</li>\r\n");
      out.write("                    <li class=\"list-inline-item\"><a href=\"#!\">Terms of Use</a></li>\r\n");
      out.write("                    <li class=\"list-inline-item\">â</li>\r\n");
      out.write("                    <li class=\"list-inline-item\"><a href=\"#!\">Privacy Policy</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <p class=\"text-muted small mb-4 mb-lg-0\">Â© Your Website 2021. All Rights Reserved.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-6 h-100 text-center text-lg-right my-auto\">\r\n");
      out.write("                <ul class=\"list-inline mb-0\">\r\n");
      out.write("                    <li class=\"list-inline-item mr-3\">\r\n");
      out.write("                        <a href=\"#!\"><i class=\"fab fa-facebook fa-2x fa-fw\"></i></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"list-inline-item mr-3\">\r\n");
      out.write("                        <a href=\"#!\"><i class=\"fab fa-twitter-square fa-2x fa-fw\"></i></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"list-inline-item\">\r\n");
      out.write("                        <a href=\"#!\"><i class=\"fab fa-instagram fa-2x fa-fw\"></i></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- Bootstrap core JS-->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<!-- Core theme JS-->\r\n");
      out.write("<script src=\"js/scripts.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
